### ISSUE TITLE
Packing = True

### ISSUE THREAD

**Issue by palash04** [pacman100/DHS-LLM-Workshop#22]
Quick Question:

You have kept packing=True. 
Shouldn't we be computing loss for the response part only? When setting packing as true, we won't get that functionality of mentioning to compute loss only for response template.
So, is it ok to train(compute loss) right from first token (including prompt) in sft?

@pacman100

**Comment by pacman100** [comment]
Hello, it depends on your use case. In general for SFT, with packing we ensure that GPU utilization is maximum and training is faster when compared to non-packing case. I would use non-packing with loss computed only on responses for tasks wherein the responses are shorter or very different from the user input, such as natural language to SQL query generation, summarization ...

**Comment by palash04** [comment]
Got it. Thanks!!
