### ISSUE TITLE
No Version mentioned for any library used in the project.

### ISSUE THREAD

**Issue by arjun-zosma** [pacman100/DHS-LLM-Workshop#33]
I tried to follow https://huggingface.co/blog/personal-copilot

But everything is breaking. Maybe because the version of the dependency needed is not mentioned. Is it not a good practice to mention the version so that we are always sure the software keeps working. How can I know which version of the dependency is compatible for the current date.

Can you please make sure to update the requirements.txt? Also, Please update the version of python dependency in the colab link as well. Referring to the PEFT one.

**Comment by Brinanet** [comment]
works by uninstalling torch, torchvision, torchaudio, and xformers
then reinstall using:
pip install torch==2.5.1 torchvision==0.20.1 torchaudio==2.5.1 xformers --index-url https://download.pytorch.org/whl/cu124
