### ISSUE TITLE
Flash Attention for fine-tuning

### ISSUE THREAD

**Issue by prince14322** [pacman100/DHS-LLM-Workshop#4]
How can we use flash attention v2 for fine-tuning with huggingface models?

Does the path only works for pre-training(or extended pre-training)?

- [Link](https://github.com/pacman100/DHS-LLM-Workshop/blob/53672e1b774da7798fb10a50ef8ca5b2750c5608/personal_copilot/training/starcoder_flash_attn_monkey_patch.py#L11)

All the discussions mentioned below are for pre-training(or extended pre-training).

- https://github.com/huggingface/accelerate/issues/1864

- https://github.com/pacman100/DHS-LLM-Workshop/issues/1

I would like to fine-tune `bigcode/starcoder` 15.5 billion parameter model with 2k context length using A100-80GB.

**Comment by cmosguy** [comment]
@prince14322 and @pacman100 

I am getting the error:

```bash
ValueError: The current architecture does not support Flash Attention 2.0. Please open an issue on GitHub to request support for this architecture: https://github.com/huggingface/transformers/issues/new
[2023-10-29 08:38:36,863] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0
```

What is going with why @pacman100  was able to run the code back in August, but now it is broken when we install the latest `transformers` from the git `main` line?  What is the solution to fixing this?

**Comment by susnato** [comment]
Hi @prince14322 , Flash Attention is now added to `StarCoder`. [PR](https://github.com/huggingface/transformers/pull/26479)
Please install from `transformers` main and and you will be able to use it for starcoder.

**Comment by younesbelkada** [comment]
Great work adding it in transformers @susnato ! That PR is part of the newest release (4.35.0) you can just do `pip install -U transformers`

**Comment by pacman100** [comment]
Hello, we have updated the code to use the FA2 support from the 🤗 transformers instead of the monkey patching. The Transformers support should handle packing as well as non packing scenarios resolving this issue.
